config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  				:controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  get 'pages/about'
  get 'myprojects' => 'project#list'
  post '/free' => 'charge#free'
  post '/pay' => 'charge#pay'

  root 'project#index'

  resources :project do
    resources :task, only: [:show]
  end

  resources :project do
    resources :reviews, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer indigo lighten-2">
   <div class="container">
      <div class="row">
         <div class="col l6 s12">
            <h5 class="white-text">Skill Mentor Academy</h5>
            <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
        </div>
        <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Social</h5>
            <ul>
               <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
               <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
               <li><a class="grey-text text-lighten-3" href="#!">Google Plus</a></li>
               <li><a class="grey-text text-lighten-3" href="#!">Linked In</a></li>
           </ul>
       </div>
   </div>
</div>
<div class="footer-copyright">
  <div class="container">
     © 2017 Copyright Skill Mentor Academy
     <%= link_to "About Us", pages_about_path, :class => "grey-text text-lighten-4 right" %>
 </div>
</div>
</footer>

app/views/shared/_header.html.erb
<header>
  <!-- Dropdown structure -->
  <ul id="dropdown1" class="dropdown-content mask">
    <li><%= link_to "My Profile", edit_user_registration_path %></li>
    <li><%= link_to "My projects", myprojects_path %></li>
    <li class="divider"></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>

  </ul>

  <!-- This second is for the mobile view -->
  <ul id="dropdown2" class="dropdown-content mask">
    <li><%= link_to "My Profile", edit_user_registration_path %></li>
    <li><%= link_to "My projects", myprojects_path %></li>
    <li class="divider"></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
  </ul>


  <nav class="indigo lighten-2 z-depth-2">
   <div class="container">
    <div class="nav-wrapper">
      <!--<a href="#!" class="brand-logo">Skill Mentor Academy</a>-->
      <%= link_to "Skill Mentor Academy", root_path, class: "brand-logo" %>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to "Projects", root_path %></li>
        <% if(!user_signed_in?)%>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% else %>
        <!-- Dropdow trigger -->
        <li>
        
        <a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown1">
        
          <%= image_tag avatar_url(current_user), class: "circle responsive-img avatar-small" %>&nbsp;
          <%= current_user.name %><i class="mdi-navigation-arrow-drop-down right"></i></a>
        
          </li>
        <% end %>
      </ul>

      <ul class="side-nav" id="mobile-demo">
        <li><a href="#">Courses</a></li>
        <% if(!user_signed_in?)%>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% else %>
        <!-- Dropdown trigger -->
        <li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown2">
          <%= image_tag avatar_url(current_user), class: "circle responsive-img avatar-small" %>&nbsp;
          <%= current_user.name %><i class="mdi-navigation-arrow-drop-down right"></i></a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
</header>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |f| %>
		<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
			toastr['<% type %>']('<%= f[1] %>')
		<% end %>
	</script>
<% end %>