config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  				:controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  get 'pages/about'
  get 'myprojects' => 'project#list'
  post '/free' => 'charge#free'
  post '/pay' => 'charge#pay'

  root 'project#index'

  resources :project do
    resources :task, only: [:show]
  end

  resources :project do
    resources :reviews, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
	extend FriendlyId
	friendly_id :name, use: [:slugged, :finders]
	has_many :tasks

	has_many :subscriptions
	has_many :users, through: :subscriptions

	has_many :reviews

	validates :name, presence: true, length: { maximum: 50 }
	validates :content, presence: true, length: { maximum: 500 }
	validates :price, presence: true, numericality: { only_integer: true }

	has_attached_file :image, styles: { medium: "680x300>", thumb: "170x75>" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  	def shortname
  		name.length > 25? name[0..25] + "..." : name
  	end

  	def average_rating
  		reviews.blank? ? 0 : reviews.average(:star).round(2)
  	end

  	def price_in_cents
  		price*100
  	end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController

  before_action :authenticate_user!, only: [:list]
  # Mostrar a lista dos projetos pertencente a um utilizador:

  def index
  	@projects = Project.all
  end

  def show
  	@project = Project.find(params[:id])
  	@tasks = @project.tasks.order(:tag)

  	@joined = false

  	if !current_user.nil? && !current_user.projects.nil?
  		#if current_user is logged in and if it has project
  		@joined = current_user.projects.include?(@project)
  	end

  	@users = @project.users.order('created_at desc').first(10)

    @review = Review.new
    @reviews = @project.reviews

    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def list
    if !current_user.nil?
      @projects = current_user.projects
    end
  end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/project/index.html.erb
<div class="row" data-no-turbolink>
	<br/>

	<% @projects.each do |project| %>
	<%= link_to project do %>
		<div class="col s12 m6 l4">
			<div class="card">
				<div class="card-image " style="height: 18em">
					<%= image_tag project.image %>
				</div><br/>

				<hr>
				<!-- <div class="center">
					<button class="btn btn-pink">Add to cart</button>
				</div> -->
				<div class="card-content" style="height: 6em">
					<span class="card-title grey-text text-darken-1">
						<h5><%= project.shortname %></h5>
					</span>
					
				</div>
			</div>
		</div>
	<% end %>
	<% end %>
</div>

app/views/project/list.html.erb
<div class="row" data-no-turbolink>
	<br/>

	<% if @projects.count > 0 %> <!-- Significa que o utilizador tem um projecto, entao vamos mostrar a lista de projetos -->

		<% @projects.each do |project| %>
			<%= link_to project do %>
				<div class="col s12 m6 l4">
					<div class="card">
						<div class="card-image ">
							<%= image_tag project.image %>
						</div>

						<div class="card-content" style="height: 6em">
							<span class="card-title grey-text text-darken-1">
								<%= project.shortname %>
							</span>
					
						</div>
				
					</div>
				</div>
			<% end %>
		<% end %>
	<% else %>
		<!-- Display a message that just say: -->
		<div class="center">
			<h5>Currently you're not in any projects!</h5>
			<%= link_to "Show me all the projects", root_path, class: "btn btn-primary"%>
		</div>

	<% end %>
</div>

app/views/project/show.html.erb
<% content_for :head do %>

	<title><%= @project.name %> | Skill Mentor Academy</title>

	<!-- twitter card data -->
	<meta name="twitter:card" content="summary_large_image">
	<meta name="twitter:site" content="@skillmentoracademy">
	<meta name="twitter:creator" content="@skillmentoracademy">
	<meta name="twitter:title" content="<%= @project.name %>">
	<meta name="twitter:description" content="<%= @project.content %>">
	<meta name="twitter:image:src" content="<%= image_url @project.image %>">

	<!-- Open Graph data -->
	<meta property="og:site_name" content="Skill Mentor Academy">
	<meta property="og:type" content="website">
	<meta property="og:title" content="<%= @project.name %>">
	<meta property="og:description" content="<%= @project.content %>">
	<meta property="og:image" content="<%= @project.image %>">

<% end %>
<div class="row" data-no-turbolink>
	<div class="col m2">
		<div class="card z-depth-1">
			<!-- check if the user is logged In-->
			<% if !@joined %>
				<div class="center">
					<h3><%= @project.price == 0? "Free" : "€#{@project.price}" %></h3>
				</div>

				<div class="card-action center">
					<% if user_signed_in? %>
						<% if @project.price == 0 %>
							<%= form_tag free_path do %>
								<%= hidden_field_tag 'project_id', @project.id %>
								<button type="submit" class="btn pink darken-2">Take this Project</button>
							<% end %> <!-- expected end -->
						<% else %>
							<%= form_tag pay_path, id: 'chargeForm' do %>
								<script src="https://checkout.stripe.com/checkout.js"></script>
								<%= hidden_field_tag 'stripeToken'%>
								<%= hidden_field_tag 'stripeEmail'%>
								<%= hidden_field_tag 'project_id', @project.id %>
								<button id="customButton" type="button" class="btn pink darken-2">Take this project</button><br/>

								<script>
									var handler = StripeCheckout.configure({
										key: '<%= Rails.configuration.stripe[:publishable_key]%>',
										image: 'https://stripe.com/img/documentation/checkout/marketplace.png',
										locale: 'auto',
										token: function(token, arg) {
	    									$('#stripeToken').val(token.id);
	    									$('#stripeEmail').val(token.email);
	    									$('#chargeForm').submit();
										}
									});

									document.getElementById('customButton').addEventListener('click', function(e) {
	  									// Open Checkout with further options:
	  									handler.open({
	  										name: 'Skill Mentor Academy',
	  										description: '<%= @project.name %>',
	  										currency: 'eur',
	  										amount: '<%= @project.price_in_cents %>',
	  										email: '<%= current_user.email %>'
	  									});
	  									e.preventDefault();
									});
								</script>
							<% end %>
						<% end %>

					<% else %>
							<%= link_to new_user_session_path do %>
							<button type="submit" class="btn pink darken-2">Take this Project</button>
							<% end %>
					<% end %>
				</div>

			<% else %>
				<div class="card-content center">
					<br/>
					<%= image_tag avatar_url(current_user), class: "circle responsive-img avatar-medium"%><br/>
					<h5 class="chip"><%= current_user.name %></h5>&nbsp;
				</div>
				<div class="card-action center">
					<div class="chip">
						Students
					</div>
					<br/>
				
					<% @users.each do |u| %>
					<div class="chip">
					<!--<span class="valign-wrapper">-->
						<%= image_tag avatar_url(u)%>
						
						<%= u.name %>

					<!--</span><br/>-->
					</div>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>

	<div class="col m10">
		<div class="card z-depth-2">
			<div class="card-image">
				<p><%= image_tag @project.image %></p>
			</div>

			<div class="row">
				<div class="col s12"><!-- antes era apenas s10 -->
					<ul class="tabs">
						<li class="tab col s3"><a class="active" href="#about">About</a></li>
						<li class="tab col s3"><a  href="#videos">Videos</a></li>
						<li class="tab col s3"><a href="#discussions">Discussions</a></li>
					</ul>
				</div>

				<div id="about" class="col s12"> <!-- antes era s12 -->
					<div class="card-content grey-text text-darken-4">
						<h5><%= @project.name %></h5>
						<span id="average_rating"></span>
						<p>
							<%= @reviews.count %>&nbsp;<%= @reviews.count > 1? "Reviews": "Review"%>
						</p>
						<hr>
						<%= @project.content %>
						<h4>Reviews</h4>
						<div><%= render 'reviews/form' if @joined && !@hasReview %></div>
						<div><%= render 'reviews/index' %></div>
					</div>
				</div>

				<div id="videos" class="col s10 offset-s1">
					<div class="collection" data-no-turbolink>
						<% @tasks.each do |task| %>
						<% if task.header %>
						<div class="collection-item active">
							<i class="mdi-social-school"><%= task.title %></i><span class="badge">1</span>
						</div>
						<% else %>
						<%= link_to [task.project, task], class: "collection-item" do %>
						<%= task.title %><span class="badge">5.00</span>
						<% end %>
						<% end %>
						<% end %>
					</div>
				</div>

				
				<div id="discussions" class="col s10 offset-s1">
					<!-- Discussion would be here -->
					<div id="disqus_thread"></div>
					<script>

						/**
						*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
						*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
						/*
						var disqus_config = function () {
						this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
						this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
						};
						*/
						var disqus_shortname = 'skillmentoracademy';
						var disqus_identifier = '<%= @project.id %>';
						(function() { // DON'T EDIT BELOW THIS LINE
							var d = document, s = d.createElement('script');
							s.src = '//skillmentoracademy.disqus.com/embed.js';
							s.setAttribute('data-timestamp', +new Date());
							(d.head || d.body).appendChild(s);
						})();
					</script>
					<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
				
				</div>
			</div>
		</div>
	</div>		
</div>
<script>
	$('#average_rating').raty({
		path: '/assets',
		readOnly: true,
		score: <%= @project.average_rating %>
	});	
</script>